#!/bin/bash
# CIS Benchmark 1.5.2 - Ensure ptrace_scope is restricted (Automated)
# Profile: Level 1 - Server, Level 1 - Workstation
#
# Remediation: Set kernel.yama.ptrace_scope to 1 (restricted ptrace)
#
# NOTE: Ubuntu ships with /etc/sysctl.d/10-ptrace.conf by default.
# This script uses a dedicated file /etc/sysctl.d/60-ptrace_scope.conf
# to ensure our setting takes precedence (higher number = loaded later)

remediate_ptrace_scope() {
    local l_parameter_name="kernel.yama.ptrace_scope"
    local l_parameter_value="1"  # Using restricted mode (value 1) as default
    local l_sysctl_file="/etc/sysctl.d/60-ptrace_scope.conf"
    
    echo "Setting $l_parameter_name to $l_parameter_value..."
    
    # Create directory if it doesn't exist
    if [ ! -d "/etc/sysctl.d" ]; then
        mkdir -p /etc/sysctl.d
    fi
    
    # Comment out (not delete) any existing entries to preserve original config
    for l_file in /etc/sysctl.conf /etc/sysctl.d/*.conf; do
        if [ -f "$l_file" ] && [ "$l_file" != "$l_sysctl_file" ]; then
            # Only modify if there's an uncommented entry
            if grep -Eq "^[^#]*$l_parameter_name\s*=" "$l_file" 2>/dev/null; then
                echo " - Commenting out existing entry in $l_file"
                sed -i "s/^\([^#]*$l_parameter_name\s*=\)/# \1/" "$l_file"
            fi
        fi
    done
    
    # Check and update UFW sysctl file if exists
    if [ -f /etc/default/ufw ]; then
        local l_ufwscf
        l_ufwscf="$(awk -F= '/^\s*IPT_SYSCTL=/ {print $2}' /etc/default/ufw | tr -d '"')"
        if [ -n "$l_ufwscf" ] && [ -f "$l_ufwscf" ]; then
            if grep -Eq "^[^#]*$l_parameter_name\s*=" "$l_ufwscf" 2>/dev/null; then
                echo " - Commenting out existing entry in $l_ufwscf"
                sed -i "s/^\([^#]*$l_parameter_name\s*=\)/# \1/" "$l_ufwscf"
            fi
        fi
    fi
    
    # Create or overwrite our dedicated configuration file
    echo " - Writing $l_parameter_name=$l_parameter_value to $l_sysctl_file"
    cat > "$l_sysctl_file" << EOF
# CIS Benchmark 1.5.2 - Ensure ptrace_scope is restricted
# Generated by remediation script on $(date)
# Values: 1=restricted, 2=admin-only, 3=no attach (irreversible)
$l_parameter_name=$l_parameter_value
EOF
    
    # Set the active kernel parameter
    echo " - Applying to running kernel..."
    if sysctl -w "$l_parameter_name=$l_parameter_value" > /dev/null 2>&1; then
        echo " - Successfully set $l_parameter_name to $l_parameter_value in running configuration"
    else
        echo " - WARNING: Failed to set $l_parameter_name in running configuration"
        echo "   Yama LSM may not be enabled in the kernel"
        return 1
    fi
    
    echo ""
    echo "Remediation complete."
    echo ""
    echo "Configuration saved to: $l_sysctl_file"
    echo ""
    echo "Value meanings:"
    echo "  1 = Restricted ptrace (only descendants can be traced)"
    echo "  2 = Admin-only attach (requires CAP_SYS_PTRACE)"
    echo "  3 = No attach (ptrace completely disabled, irreversible until reboot)"
    echo ""
    echo "If a value of 2 or 3 is required by local site policy,"
    echo "edit $l_sysctl_file and run: sysctl -p $l_sysctl_file"
    
    return 0
}

remediate_ptrace_scope
